# Generated by Django 3.2.6 on 2022-04-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chemistry_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=200)),
                ('reagent_lot', models.CharField(max_length=100, unique=True)),
                ('reagent_lot_expiration', models.DateField()),
                ('current_lot', models.BooleanField()),
                ('reagent_quantity', models.IntegerField()),
                ('warning_amount', models.IntegerField()),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chemistry Inventory',
                'verbose_name_plural': 'Chemistry Inventory',
            },
        ),
        migrations.CreateModel(
            name='hematology_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=200)),
                ('reagent_lot', models.CharField(max_length=100, unique=True)),
                ('reagent_lot_expiration', models.DateField()),
                ('current_lot', models.BooleanField()),
                ('reagent_quantity', models.IntegerField()),
                ('warning_amount', models.IntegerField()),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hematology Inventory',
                'verbose_name_plural': 'Hematology Inventory',
            },
        ),
        migrations.CreateModel(
            name='historical_chemistry_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_used', models.IntegerField()),
                ('reagent_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('reagent_name_history', models.CharField(max_length=100)),
                ('reagent_lot_history', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Historical Chemistry Inventory',
                'verbose_name_plural': 'Historical Chemistry Inventory',
            },
        ),
        migrations.CreateModel(
            name='historical_hematology_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_used', models.IntegerField()),
                ('reagent_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('reagent_name_history', models.CharField(max_length=100)),
                ('reagent_lot_history', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Historical Hematology Inventory',
                'verbose_name_plural': 'Historical Hematology Inventory',
            },
        ),
        migrations.CreateModel(
            name='specialist_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hematology_specialist', models.BooleanField()),
                ('chemistry_specialist', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='specialist_preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_when_low', models.BooleanField(help_text='Email will be sent when reagent gets to warning level')),
                ('alert_for_expiration_yes_or_no', models.BooleanField()),
                ('alert_for_expiration', models.IntegerField(blank=True, help_text='Chose days before expiration to receive a warning email.  Leave blank if you do not want to recieve expiration emails.', null=True)),
                ('alert_when_empty', models.BooleanField(help_text='Send email when reagent is empty')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialist Preferences',
                'verbose_name_plural': 'Specialist Preferences',
            },
        ),
    ]
