# Generated by Django 3.2.6 on 2022-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_specialist_preferences_alert_for_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist_preferences',
            name='alert_for_expiration',
            field=models.IntegerField(help_text='Chose days before expiration to receive a warning email.  Leave blank if you do not want to recieve expiration emails.', null=True),
        ),
    ]
