# Generated by Django 3.2.6 on 2022-04-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_specialist_preferences_alert_for_expiration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='specialist_setup',
        ),
    ]
