# Generated by Django 3.2.6 on 2022-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_specialist_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry_inventory',
            name='reagent_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hematology_inventory',
            name='reagent_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
